on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Generate the artifacts
        run : |
           pwd
           ls -l
           sudo apt-get update
           sudo apt install libusb-1.0-0-dev
           sudo apt install libieee1284-3-dev
           sudo apt install libcurl4-openssl-dev
           sudo apt install libsndfile1-dev
           sudo apt install libasound-dev
           sudo apt install libudev-dev
           sudo apt-get install fpc
           cd src
           make distclean
           make
           make clean
           ./pcprint
           echo Done
           cd ..
