on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Generate the artifacts
        run : |
          sudo apt-get update
          sudo apt install -y jq
#          sudo apt install curl
#          sudo apt install libusb-1.0-0-dev
#          sudo apt install libieee1284-3-dev
#          sudo apt install libcurl4-openssl-dev
#          sudo apt install libsndfile1-dev
#          sudo apt install libasound-dev
#          sudo apt install libudev-dev
          sudo apt-get install fpc
          pwd
          ls -l
          cd src
          make distclean
          make
          make clean
          ./pcprint
          echo Done
          cd ..
      - name: Upload the artifacts
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
           upload_url: ${{ github.event.release.upload_url }}
           asset_path: src/pcprint
           asset_name: pcprint
           asset_content_type: application/octet-stream
